# Generated by Django 5.0.6 on 2024-08-01 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefnote',
            name='dateOfAppointment',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
